### ISSUE TITLE
Algorithm used for consensus?

### ISSUE THREAD

**Issue by baboune** [Ericsson/paf#15]
What does pathfinder use for consensus resolution/decision making?

**Comment by m-ronnblom** [comment]
Pathfinder has no consensus protocol. It does not, in its current form, attempt to address the case of a server suffering a Byzantine failure.

If Pathfinder were to, for example, mitigate the effects of a malicious server, I'm not sure the solution would have to involve a consensus protocol. There's no need reach global agreement, and it seemed like it could reduced to an entirely client library-local affair. I might well be missing something though.

**Comment by baboune** [comment]
The README mentions "state" usually in a distributed system a consensus algorithm could be used.
